### ISSUE TITLE
can't upgrade dependency `tipb` in `tikv`

### ISSUE THREAD

**Issue by qw4990** [tikv/tikv#4864]
## Bug Report
I want to introduce a new function signature to fix this MySQL-compatibility problem(https://github.com/pingcap/tidb/issues/9763);

After I upgrade `tipb` from the specific version `tipb/833c2f` to `tipb/master`, I get some errors when building:
```
error: failed to select a version for `protobuf`.
    ... required by package `tipb v0.0.1 (https://github.com/pingcap/tipb.git)`
    ... which is depended on by `cop_datatype v0.0.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv/components/cop_datatype)`
    ... which is depended on by `tikv v3.0.0-beta.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv)`
    ... which is depended on by `fuzz-targets v0.0.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv/fuzz/targets)`
    ... which is depended on by `fuzzer-afl v0.0.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv/fuzz/fuzzer-afl)`
versions that meet the requirements `^2.1` are: 2.6.2, 2.6.1, 2.6.0, 2.5.0, 2.4.2, 2.4.0, 2.3.1, 2.3.0, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0

all possible versions conflict with previously selected packages.

  previously selected package `protobuf v2.0.4`
    ... which is depended on by `codec v0.0.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv/components/codec)`
    ... which is depended on by `tikv v3.0.0-beta.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv)`
    ... which is depended on by `fuzz-targets v0.0.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv/fuzz/targets)`
    ... which is depended on by `fuzzer-afl v0.0.1 (/Users/zhangyuanjia/Workspace/go/src/github.com/pingcap/tikv/fuzz/fuzzer-afl)`

failed to select a version for `protobuf` which could resolve this conflict
```

The specific version is hard-wrriten in `Cargo.lock`:
```
[[package]]
name = "tipb"
version = "0.0.1"
source = "git+https://github.com/pingcap/tipb.git#833c2ffd2fe7aad5224dd7c2b05fb24bc109e969"
dependencies = [
 "protobuf 2.0.4 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**Comment by nrc** [comment]
This is fixed by relaxing the Protobuf dependency everywhere. That requires PRs to a few repos. Once https://github.com/pingcap/tipb/pull/124 and https://github.com/pingcap/kvproto/pull/416 land, then I can submit a PR here to fix the issue.

**Comment by eurekaka** [comment]
@nrc Great to hear that, thanks for the effort.

**Comment by breeswish** [comment]
For now you can propose kvproto / tipb PRs to both master and release-3.0 branch.

**Comment by nrc** [comment]
PRs have landed in KvProto, TiPB, and TiKV. So you should now be able to update the TiPB dep (I didn't update myself in case you wanted to make changes to TiKV at the same time). Let me know if there is anything else which needs fixing.

**Comment by eurekaka** [comment]
@nrc Looks like the problem still exists:
```
[cauchy@kenan ~/workspace/tikv]$ cargo update -p tipb
    Updating git repository `https://github.com/pingcap/tipb.git`
    Updating crates.io index
error: failed to select a version for `protobuf`.
    ... required by package `protoc-grpcio v1.0.2`
    ... which is depended on by `protobuf-build v0.6.0`
    ... which is depended on by `tipb v0.0.1 (https://github.com/pingcap/tipb.git#87cb1e27)`
    ... which is depended on by `cop_datatype v0.0.1 (/Users/cauchy/workspace/tikv/components/cop_datatype)`
    ... which is depended on by `tikv v4.0.0-alpha (/Users/cauchy/workspace/tikv)`
    ... which is depended on by `fuzz-targets v0.0.1 (/Users/cauchy/workspace/tikv/fuzz/targets)`
    ... which is depended on by `fuzzer-afl v0.0.1 (/Users/cauchy/workspace/tikv/fuzz/fuzzer-afl)`
versions that meet the requirements `^2.1` are: 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.0, 2.4.2, 2.4.0, 2.3.1, 2.3.0, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0

all possible versions conflict with previously selected packages.

  previously selected package `protobuf v2.0.4`
    ... which is depended on by `protobuf-codegen v2.0.4`
    ... which is depended on by `grpcio-compiler v0.4.3`
    ... which is depended on by `protobuf-build v0.1.0`
    ... which is depended on by `kvproto v0.0.1 (https://github.com/pingcap/kvproto.git?branch=release-3.0#053b13a9)`
    ... which is depended on by `engine v0.0.1 (/Users/cauchy/workspace/tikv/components/engine)`
    ... which is depended on by `test_raftstore v0.0.1 (/Users/cauchy/workspace/tikv/components/test_raftstore)`
    ... which is depended on by `test_storage v0.0.1 (/Users/cauchy/workspace/tikv/components/test_storage)`
    ... which is depended on by `test_coprocessor v0.0.1 (/Users/cauchy/workspace/tikv/components/test_coprocessor)`
    ... which is depended on by `tikv v4.0.0-alpha (/Users/cauchy/workspace/tikv)`
    ... which is depended on by `fuzz-targets v0.0.1 (/Users/cauchy/workspace/tikv/fuzz/targets)`
    ... which is depended on by `fuzzer-afl v0.0.1 (/Users/cauchy/workspace/tikv/fuzz/fuzzer-afl)`

failed to select a version for `protobuf` which could resolve this conflict
```
Could you please help to take a look? or is there anything missed in my steps?

**Comment by nrc** [comment]
Can you update kvproto as well as tipb? It might be that we need to pin to a later commit of kvproto.

**Comment by eurekaka** [comment]
Do you mean:
```
cargo update -p kvproto; cargo update -p tipb
```
? still cannot work

**Comment by kennytm** [comment]
kvproto's `protobuf-build` dependency in the ***release-3.0*** branch needs to be bumped from 0.1 to 0.6.

**Comment by nrc** [comment]
Ah, ok, then I think we are waiting for https://github.com/pingcap/kvproto/pull/426 and then we should be OK (note that PR means TiKV can depend on master, not release-3.0)

**Comment by nrc** [comment]
I think this is fixed now. @qw4990 could you confirm please?

**Comment by nrc** [comment]
Closing, since I think this is fixed. Please let me know if not.
